name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Python 3.10
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: pip install -r report/src/report/requirements-dev.txt

      - name: Execute pytest
        run: pytest report/src/report --cov-report term-missing --cov=report/src/report
        env:
          PYTHONPATH: report/src/report
